# Generated by Django 4.2.29 on 2026-03-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='color',
        ),
        migrations.AlterField(
            model_name='face',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
