# Generated by Django 4.2.29 on 2026-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0002_remove_face_color_alter_face_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
