# Generated by Django 4.2.29 on 2026-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0003_face_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='metadata',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
