# Generated by Django 4.2.29 on 2026-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0004_alter_face_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
