# Generated by Django 4.2.29 on 2026-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0005_face_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
