# Generated by Django 4.2.29 on 2026-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0006_face_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
