# Generated by Django 4.2.29 on 2026-03-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_stream', '0007_face_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='summary',
        ),
    ]
