# Audio configuration constants
TARGET_SAMPLE_RATE = 16000
DEFAULT_SOURCE_SAMPLE_RATE = 48000
BUFFER_THRESHOLD = 100
ROLLING_TAIL_SIZE = 25
NEW_DATA_SIZE = 75 # Based on (100 - 25)
SILENCE_THRESHOLD = 0.005
MIN_SIGNAL_FOR_NORMALIZATION = 0.001
MAX_TRANSCRIPTION_HISTORY = 5
MAX_HISTORY_PROMPT_SIZE = 3

# Face matching constants
FACE_DISTANCE_THRESHOLD = 0.6

# Transcription configuration
WHISPER_MODEL_NAME = "base.en"
WHISPER_BEAM_SIZE = 2
WHISPER_FP16 = False
WHISPER_LANGUAGE = "en"
WHISPER_CONDITION_ON_PREVIOUS_TEXT = True
